########################
#
# UNICO PROJECT USERS MICRO SERVICE
#
########################

spring:
  application:
    name: exchange-svc
  profiles:
    active: local
  eueka:
    instance:
      preferIpAddress: true
      client:
        registerWithEureka: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  kafka:
    consumer:
      group-id: exchange-svc
      bootstrap-servers: 13.125.208.139:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 13.125.208.139:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
--- #local env
spring:
  profiles: local
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/exchange_msa
    name: hjkim
    password: dusrn!23

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8086
  servlet:
    context-path: /
--- #dev env
spring:
  profiles: dev

--- #prod env
spring:
  profiles: prod

server:
  port: 8086

